baseURL: https://nixvim-options.extranix.com/
languageCode: en-us
title: NixVim - Option Search
theme: extranix-options-search

params:

  release_current_stable: nixos-25.11
  releases:
    - name: unstable
      value: main
    - name: 25.11 (stable)
      value: nixos-25.11
    - name: 25.05
      value: nixos-25.05
    - name: 24.11
      value: nixos-24.11
    - name: 24.05
      value: nixos-24.05

  release_switch_title: NixVim Release

  # TODO update
  custom_head_scripts: |
    <script async src="https://umami.pimsnel.com/script.js" data-website-id="8e970d59-b517-4ba6-9b92-207e7dbdb4b1"></script>
    <script async src="https://media.ethicalads.io/media/client/ethicalads.min.js"></script>

  custom_header_tags: <div id="eadiv" data-ea-publisher="extranixcom" data-ea-type="text"></div>

  footer_credits_line: |
    Powered by the <a href="https://nix-community.org/">Nix Community</a> |
    <a href="https://github.com/ekstranix/nixvim-option-search#credits">Credits</a> |
    <a href="https://nix-community.github.io/nixvim/">NixVim Documentation</a>

  footer_copyright_line: |
    Made with ❤️ by <a href="https://github.com/mipmip">Pim Snel</a> - © 2022-2026

  # TODO
  logo: images/home-manager-option-search2.png

  github:
    repo: nixvim-option-search
    user: ekstranix
    show_count: true
    show_text: true

  main_menu:

    - name: NixVim&nbsp;Documentation
      url: https://nix-community.github.io/nixvim/
      icon_class: fa fa-book

    - name: Source
      url: https://github.com/ekstranix/nixvim-option-search
      icon_class: fa fa-github

markup:
  goldmark:
    renderer:
      unsafe: true
